apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: cert-manager
deploy:
  helm:
    releases:
      - name: cert-manager
        repo: https://charts.jetstack.io
        remoteChart: cert-manager
        namespace: cert-manager
        createNamespace: true
        setValues:
          installCRDs: true
