apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: metallb
manifests:
  kustomize:
    paths:
      - ./k8s
deploy:
  helm:
    releases:
      - name: metallb
        repo: https://metallb.github.io/metallb
        remoteChart: metallb
        namespace: metallb-system
        createNamespace: true
        setValues:
          installCRDs: true
  kubectl: {}
