apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
helmCharts:
- name: rook-ceph
  repo: https://charts.rook.io/release
  releaseName: rook-ceph
  namespace: rook-ceph
  valuesFile: rook-ceph-values.yaml
- name: rook-ceph-cluster
  repo: https://charts.rook.io/release
  releaseName: rook-ceph-cluster
  namespace: rook-ceph
  valuesFile: rook-ceph-cluster-values.yaml

resources:
  - namespace.yaml