apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-prometheus-stack
helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: kube-prometheus-stack
  namespace: kube-prometheus-stack
  valuesFile: kube-prometheus-stack-values.yaml
  version: v0.68.0

resources:
  - namespace.yaml
  - issuer.yaml
  - certificates.yaml

secretGenerator:
  - name: letsencrypt-cloudflare-api-token-secret
    env: ./enviroment/letsencrypt-cloudflare-api-token-secret.env

generatorOptions:
  disableNameSuffixHash: true