apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
helmCharts:
- name: metallb
  repo: https://metallb.github.io/metallb
  releaseName: metallb
  namespace: metallb-system
  valuesFile: values.yaml
  version: v0.13.10

resources:
  - namespace.yaml
  - metallb.yaml