apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    releaseName: ingress-nginx-external
    namespace: kube-system
    valuesFile: ingress-nginx-external-values.yaml
    version: v4.8.0
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    releaseName: ingress-nginx-internal
    namespace: kube-system
    valuesFile: ingress-nginx-internal-values.yaml
    version: v4.8.0